collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1559139
color:
  saturation: 0.5310633
  brandStrength: 0.8596177
  lightness: 0.4940263
  brandColors:
    - '#000000'
    - '#FCFCFC'
    - '#9C9C9C'
    - '#575757'
    - '#DDDDDD'
  rhythmicContrast: 0.5464761
layout_spectrum: 1
name: Time Stops Here Photos
